CREATE TABLE IF NOT EXISTS user_info (
	PK_USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    USER_ROLE ENUM('Student', 'Faculty', 'Admin') NOT NULL DEFAULT ('Student'),
    FIRST_NAME VARCHAR(25) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    LAST_NAME VARCHAR(25) NOT NULL,
    STUDENT_ID VARCHAR(9) UNIQUE DEFAULT NULL,
    EMAIL_ADDRESS VARCHAR(255) UNIQUE NOT NULL,
    ACCOUNT_PASSWORD TEXT NOT NULL,
    TAG_ID TEXT,
    CHECK (EMAIL_ADDRESS LIKE '%@spu.edu')
);
